# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

#osx_image: xcode7.3
language: objective-c
xcode_workspace: Example/ZZRouter.xcworkspace
xcode_scheme: ZZRouter
xcode_sdk: iphonesimulator

